### ISSUE TITLE
KeyError: 'like_count'

### ISSUE THREAD

**Issue by Sere1nz** [akash-agni/Real-Time-Object-Detection#6]
(rtobj_dec) D:\code\Real-Time-Object-Detection>python Object_Detection_Youtube.py https://www.youtube.com/watch?v=vEypF3IAxmg testfile.avi
Using cache found in C:\Users\win10/.cache\torch\hub\ultralytics_yolov5_master
YOLOv5  2022-10-20 Python-3.8.5 torch-1.8.1+cpu CPU

Downloading https://github.com/ultralytics/yolov5/releases/download/v6.2/yolov5s.pt to yolov5s.pt...
100%|██████████████████████████████████████████████████████████████████████████████| 14.1M/14.1M [00:26<00:00, 569kB/s]

Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape...
Traceback (most recent call last):
  File "Object_Detection_Youtube.py", line 107, in <module>
    a()
  File "Object_Detection_Youtube.py", line 88, in __call__
    player = self.get_video_from_url()
  File "Object_Detection_Youtube.py", line 30, in get_video_from_url
    play = pafy.new(self._URL).streams[-1]
  File "C:\Users\win10\anaconda3\envs\rtobj_dec\lib\site-packages\pafy\pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "C:\Users\win10\anaconda3\envs\rtobj_dec\lib\site-packages\pafy\backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "C:\Users\win10\anaconda3\envs\rtobj_dec\lib\site-packages\pafy\backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "C:\Users\win10\anaconda3\envs\rtobj_dec\lib\site-packages\pafy\backend_youtube_dl.py", line 53, in _fetch_basic
    self._likes = self._ydl_info['like_count']
KeyError: 'like_count'

Hi, I got this problem. It might relate to the pafy package. How should I deal with it? Thank you!

**Comment by Sere1nz** [comment]
It turns out that `pip install youtube-dl==2020.12.2` will fix this issue. The newest version counts the "like" and "dislike" of the video, so if the video don't have any, this error will occur. I will close the issue.
